#pragma once

#define CDE_BLACK_WHITE_ENABLE_SPOKE_FILTERING 1
#define CDE_BLACK_WHITE_ENABLE_BRIDGE_FILTERING 1
#define CDE_BLACK_WHITE_FIXED_ORDER 1
#define CDE_BLACK_WHITE_COLOR_ALL_BLACK 0
#define CDE_BLACK_WHITE_COLOR_ALL_WHITE 0
#define CDE_BLACK_WHITE_COLOR1 0
#define CDE_BLACK_WHITE_RANDOM_ORDER 0
#define CDE_BLACK_WHITE_ENABLE_SPLIT 1
