#pragma once

#define CDE_EDGE_IE_TERMINAL_BUCKETS_DEFAULT 1
#define CDE_EDGE_IE_ENABLE_SPOKE_FILTERING 1
#define CDE_EDGE_IE_ENABLE_BRIDGE_FILTERING 1
#define CDE_EDGE_IE_FIXED_ORDER 0
#define CDE_EDGE_IE_TOPK_SUPPORT_DECAY 0
