#ifndef _CONFIG_H_
#define _CONFIG_H_

// Shared settings used by both default and ablation configurations.
#define NDEBUG
#define MATCH_OUTPUT_LIMIT 100000000

#ifdef SSM_GED_CONFIG_HEADER

#include SSM_GED_CONFIG_HEADER

#else

// #define ENABLE_EXCLUDED_EDGE_SUPPORT
// #define ENABLE_CAND_STATS

#define CDE_EDGE_IE_ENABLE_SPOKE_FILTERING 1
#define CDE_EDGE_IE_ENABLE_BRIDGE_FILTERING 1
#define CDE_EDGE_IE_FIXED_ORDER 0

#define CDE_BLACK_WHITE_ENABLE_SPOKE_FILTERING 1
#define CDE_BLACK_WHITE_ENABLE_BRIDGE_FILTERING 1
#define CDE_BLACK_WHITE_FIXED_ORDER 0
#define CDE_BLACK_WHITE_STATIC_COLOR 1
#define CDE_BLACK_WHITE_STATIC_COLOR_ALL_BLACK 0
#define CDE_BLACK_WHITE_TOPK_SUPPORT_DECAY 1
#define CDE_BLACK_WHITE_TOPK_SUPPORT_DECAY_GAMMA 0.9
#define CDE_BLACK_WHITE_ENABLE_SPLIT 1

#endif // SSM_GED_CONFIG_HEADER

#ifndef CDE_EDGE_IE_ENABLE_SPOKE_FILTERING
#define CDE_EDGE_IE_ENABLE_SPOKE_FILTERING 1
#endif

#ifndef CDE_EDGE_IE_ENABLE_BRIDGE_FILTERING
#define CDE_EDGE_IE_ENABLE_BRIDGE_FILTERING 1
#endif

#ifndef CDE_EDGE_IE_FIXED_ORDER
#define CDE_EDGE_IE_FIXED_ORDER 0
#endif

#ifndef CDE_BLACK_WHITE_ENABLE_SPOKE_FILTERING
#define CDE_BLACK_WHITE_ENABLE_SPOKE_FILTERING 1
#endif

#ifndef CDE_BLACK_WHITE_ENABLE_BRIDGE_FILTERING
#define CDE_BLACK_WHITE_ENABLE_BRIDGE_FILTERING 1
#endif

#ifndef CDE_BLACK_WHITE_FIXED_ORDER
#define CDE_BLACK_WHITE_FIXED_ORDER 0
#endif

#ifndef CDE_BLACK_WHITE_STATIC_COLOR
#define CDE_BLACK_WHITE_STATIC_COLOR 1
#endif

#ifndef CDE_BLACK_WHITE_STATIC_COLOR_ALL_BLACK
#define CDE_BLACK_WHITE_STATIC_COLOR_ALL_BLACK 0
#endif

#ifndef CDE_BLACK_WHITE_TOPK_SUPPORT_DECAY
#define CDE_BLACK_WHITE_TOPK_SUPPORT_DECAY 1
#endif

#ifndef CDE_BLACK_WHITE_TOPK_SUPPORT_DECAY_GAMMA
#define CDE_BLACK_WHITE_TOPK_SUPPORT_DECAY_GAMMA 0.9
#endif

#ifndef CDE_BLACK_WHITE_ENABLE_SPLIT
#define CDE_BLACK_WHITE_ENABLE_SPLIT 1
#endif

#ifndef MATCH_OUTPUT_LIMIT
#error "MATCH_OUTPUT_LIMIT must be defined by the selected configuration."
#endif

#if CDE_EDGE_IE_ENABLE_SPOKE_FILTERING != 0 && CDE_EDGE_IE_ENABLE_SPOKE_FILTERING != 1
#error "CDE_EDGE_IE_ENABLE_SPOKE_FILTERING must be 0 or 1."
#endif

#if CDE_EDGE_IE_ENABLE_BRIDGE_FILTERING != 0 && CDE_EDGE_IE_ENABLE_BRIDGE_FILTERING != 1
#error "CDE_EDGE_IE_ENABLE_BRIDGE_FILTERING must be 0 or 1."
#endif

#if CDE_EDGE_IE_FIXED_ORDER != 0 && CDE_EDGE_IE_FIXED_ORDER != 1
#error "CDE_EDGE_IE_FIXED_ORDER must be 0 or 1."
#endif

#if CDE_BLACK_WHITE_ENABLE_SPOKE_FILTERING != 0 && CDE_BLACK_WHITE_ENABLE_SPOKE_FILTERING != 1
#error "CDE_BLACK_WHITE_ENABLE_SPOKE_FILTERING must be 0 or 1."
#endif

#if CDE_BLACK_WHITE_ENABLE_BRIDGE_FILTERING != 0 && CDE_BLACK_WHITE_ENABLE_BRIDGE_FILTERING != 1
#error "CDE_BLACK_WHITE_ENABLE_BRIDGE_FILTERING must be 0 or 1."
#endif

#if CDE_BLACK_WHITE_FIXED_ORDER != 0 && CDE_BLACK_WHITE_FIXED_ORDER != 1
#error "CDE_BLACK_WHITE_FIXED_ORDER must be 0 or 1."
#endif

#if CDE_BLACK_WHITE_STATIC_COLOR != 0 && CDE_BLACK_WHITE_STATIC_COLOR != 1
#error "CDE_BLACK_WHITE_STATIC_COLOR must be 0 or 1."
#endif

#if CDE_BLACK_WHITE_STATIC_COLOR_ALL_BLACK != 0 && CDE_BLACK_WHITE_STATIC_COLOR_ALL_BLACK != 1
#error "CDE_BLACK_WHITE_STATIC_COLOR_ALL_BLACK must be 0 or 1."
#endif

#if CDE_BLACK_WHITE_TOPK_SUPPORT_DECAY != 0 && CDE_BLACK_WHITE_TOPK_SUPPORT_DECAY != 1
#error "CDE_BLACK_WHITE_TOPK_SUPPORT_DECAY must be 0 or 1."
#endif

#if CDE_BLACK_WHITE_ENABLE_SPLIT != 0 && CDE_BLACK_WHITE_ENABLE_SPLIT != 1
#error "CDE_BLACK_WHITE_ENABLE_SPLIT must be 0 or 1."
#endif

#if CDE_BLACK_WHITE_FIXED_ORDER && CDE_BLACK_WHITE_TOPK_SUPPORT_DECAY
#error "CDE_BLACK_WHITE_FIXED_ORDER and CDE_BLACK_WHITE_TOPK_SUPPORT_DECAY are mutually exclusive."
#endif

#if MATCH_OUTPUT_LIMIT < 0
#error "MATCH_OUTPUT_LIMIT must be non-negative."
#endif

#endif //_CONFIG_H_
