#ifndef _CONFIG_H_
#define _CONFIG_H_

// Shared settings used by both default and ablation configurations.
#define NDEBUG
#ifndef MATCH_OUTPUT_LIMIT
#define MATCH_OUTPUT_LIMIT 100000000
#endif

#ifdef SSM_CONFIG_HEADER

#include SSM_CONFIG_HEADER

#else

#define CDE_BLACK_WHITE_ENABLE_SPOKE_FILTERING 1
#define CDE_BLACK_WHITE_ENABLE_BRIDGE_FILTERING 1
#define CDE_BLACK_WHITE_FIXED_ORDER 0
#define CDE_BLACK_WHITE_STATIC_COLOR 1
#define CDE_BLACK_WHITE_STATIC_COLOR_ALL_BLACK 0
#define CDE_BLACK_WHITE_STATIC_COLOR_ALL_WHITE 0
#define CDE_BLACK_WHITE_TOPK_SUPPORT_DECAY 1
#define CDE_BLACK_WHITE_TOPK_SUPPORT_DECAY_GAMMA 0.9
#define CDE_BLACK_WHITE_ENABLE_SPLIT 1
#define CDE_BLACK_WHITE_USE_FLAT_HASH_MAP 1

#endif // SSM_CONFIG_HEADER

#ifndef CDE_BLACK_WHITE_ENABLE_SPOKE_FILTERING
#define CDE_BLACK_WHITE_ENABLE_SPOKE_FILTERING 1
#endif

#ifndef CDE_BLACK_WHITE_ENABLE_BRIDGE_FILTERING
#define CDE_BLACK_WHITE_ENABLE_BRIDGE_FILTERING 1
#endif

#ifndef CDE_BLACK_WHITE_FIXED_ORDER
#define CDE_BLACK_WHITE_FIXED_ORDER 0
#endif

#ifndef CDE_BLACK_WHITE_STATIC_COLOR
#define CDE_BLACK_WHITE_STATIC_COLOR 1
#endif

#ifndef CDE_BLACK_WHITE_STATIC_COLOR_ALL_BLACK
#define CDE_BLACK_WHITE_STATIC_COLOR_ALL_BLACK 0
#endif

#ifndef CDE_BLACK_WHITE_STATIC_COLOR_ALL_WHITE
#define CDE_BLACK_WHITE_STATIC_COLOR_ALL_WHITE 0
#endif

#ifndef CDE_BLACK_WHITE_TOPK_SUPPORT_DECAY
#define CDE_BLACK_WHITE_TOPK_SUPPORT_DECAY 1
#endif

#ifndef CDE_BLACK_WHITE_TOPK_SUPPORT_DECAY_GAMMA
#define CDE_BLACK_WHITE_TOPK_SUPPORT_DECAY_GAMMA 0.9
#endif

#ifndef CDE_BLACK_WHITE_ENABLE_SPLIT
#define CDE_BLACK_WHITE_ENABLE_SPLIT 1
#endif

#ifndef CDE_BLACK_WHITE_USE_FLAT_HASH_MAP
#define CDE_BLACK_WHITE_USE_FLAT_HASH_MAP 1
#endif

#ifndef MATCH_OUTPUT_LIMIT
#error "MATCH_OUTPUT_LIMIT must be defined by the selected configuration."
#endif

#if CDE_BLACK_WHITE_ENABLE_SPOKE_FILTERING != 0 && CDE_BLACK_WHITE_ENABLE_SPOKE_FILTERING != 1
#error "CDE_BLACK_WHITE_ENABLE_SPOKE_FILTERING must be 0 or 1."
#endif

#if CDE_BLACK_WHITE_ENABLE_BRIDGE_FILTERING != 0 && CDE_BLACK_WHITE_ENABLE_BRIDGE_FILTERING != 1
#error "CDE_BLACK_WHITE_ENABLE_BRIDGE_FILTERING must be 0 or 1."
#endif

#if CDE_BLACK_WHITE_FIXED_ORDER != 0 && CDE_BLACK_WHITE_FIXED_ORDER != 1
#error "CDE_BLACK_WHITE_FIXED_ORDER must be 0 or 1."
#endif

#if CDE_BLACK_WHITE_STATIC_COLOR != 0 && CDE_BLACK_WHITE_STATIC_COLOR != 1
#error "CDE_BLACK_WHITE_STATIC_COLOR must be 0 or 1."
#endif

#if CDE_BLACK_WHITE_STATIC_COLOR_ALL_BLACK != 0 && CDE_BLACK_WHITE_STATIC_COLOR_ALL_BLACK != 1
#error "CDE_BLACK_WHITE_STATIC_COLOR_ALL_BLACK must be 0 or 1."
#endif

#if CDE_BLACK_WHITE_STATIC_COLOR_ALL_WHITE != 0 && CDE_BLACK_WHITE_STATIC_COLOR_ALL_WHITE != 1
#error "CDE_BLACK_WHITE_STATIC_COLOR_ALL_WHITE must be 0 or 1."
#endif

#if CDE_BLACK_WHITE_TOPK_SUPPORT_DECAY != 0 && CDE_BLACK_WHITE_TOPK_SUPPORT_DECAY != 1
#error "CDE_BLACK_WHITE_TOPK_SUPPORT_DECAY must be 0 or 1."
#endif

#if CDE_BLACK_WHITE_ENABLE_SPLIT != 0 && CDE_BLACK_WHITE_ENABLE_SPLIT != 1
#error "CDE_BLACK_WHITE_ENABLE_SPLIT must be 0 or 1."
#endif

#if CDE_BLACK_WHITE_USE_FLAT_HASH_MAP != 0 && CDE_BLACK_WHITE_USE_FLAT_HASH_MAP != 1
#error "CDE_BLACK_WHITE_USE_FLAT_HASH_MAP must be 0 or 1."
#endif

#if CDE_BLACK_WHITE_FIXED_ORDER && CDE_BLACK_WHITE_TOPK_SUPPORT_DECAY
#error "CDE_BLACK_WHITE_FIXED_ORDER and CDE_BLACK_WHITE_TOPK_SUPPORT_DECAY are mutually exclusive."
#endif

#if CDE_BLACK_WHITE_STATIC_COLOR_ALL_BLACK && CDE_BLACK_WHITE_STATIC_COLOR_ALL_WHITE
#error "CDE_BLACK_WHITE_STATIC_COLOR_ALL_BLACK and CDE_BLACK_WHITE_STATIC_COLOR_ALL_WHITE are mutually exclusive."
#endif

#if MATCH_OUTPUT_LIMIT < 0
#error "MATCH_OUTPUT_LIMIT must be non-negative."
#endif

#endif //_CONFIG_H_
