#pragma once

#define AFEE_ENABLE_SPOKE_FILTERING 1
#define AFEE_ENABLE_BRIDGE_FILTERING 1
#define AFEE_FIXED_ORDER 0
#define AFEE_DYNAMIC_ORDER 0
#define AFEE_RANDOM_ORDER 1
#define AFEE_COLOR_ALL_BLACK 0
#define AFEE_COLOR_ALL_WHITE 0
#define AFEE_DYNAMIC_COLOR 1
#define AFEE_ENABLE_SPLIT 1
